apiVersion: v1
kind: Service
metadata:
    name: "kubclust-c308"
    labels:
        app: "kubclust-c308"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "kubclust-c308"